### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by it-sam** [synw/geopoint#6]
Could you please migrate to Dart's new null safety? https://dart.dev/null-safety/migration-guide

**Comment by it-sam** [comment]
https://github.com/synw/geopoint/pull/8

**Comment by neokree** [comment]
My project could not upgrade to flutter 2.2 because of this issue. Could you speed up the pull request revision?

**Comment by neokree** [comment]
For those interested, I also found out a new package called geopoint2: https://pub.dev/packages/geopoint2

However, I don't think it's a good idea, since It's a workaround for the real issue (and the main problem are other packages that depends on this one, like https://github.com/synw/geojson/issues/37).

**Comment by it-sam** [comment]
@neokree  By the time the  [pull request](https://github.com/synw/geopoint/pull/8) get approved, 
Alternative is here. Add this into your **yaml** file.
**For Geo Json:** 

    dependency_overrides:

	  geojson:
	    git:
  
	      url: https://github.com/it-sam/geojson.git
      
	      commit: 6fa3b9
      
  **For Geo point**
  
  
	  dependency_overrides:
  
	  geopoint:
  
	    git:
    
	      url: https://github.com/it-sam/geopoint.git
      
	      commit: 7a28e2

**Comment by neokree** [comment]
@it-sam Thanks for pointing that out I didn't know it was possible to override a dependency that way!

Unfortunately in my case I need a stable solution since my app must be production ready, so I will wait until all packages will be upgraded to null-safety.

**Comment by neokree** [comment]
@it-sam @synw I think we should close this issue now that #8 is merged
